### ISSUE TITLE
Unsupported operand

### ISSUE THREAD

**Issue by datatalking** [khuyentran1401/Task-scheduler-problem#2]
I've been looking for a time blocking script and found yours to be pretty good.

When I run the notebook it throws an error in block [6]

In pandas documentation, they say you can 

A list or array of integers, e.g. [4, 3, 0].
A slice object with ints, e.g. 1:7.

Does it seem correct that you are trying to slice an object as an array of integers?

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-4ad0f3fbd9df> in <module>
      1 #Time blocks available
----> 2 A = sum(b)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

**Comment by khuyentran1401** [comment]
Hi, are you trying this with an excel sheet? Do you have b as a list like this? b = list(schedule.iloc[:,0]). And yes, b is an array of integers
