### ISSUE TITLE
Missing: csv file and !pip imports

### ISSUE THREAD

**Issue by datatalking** [khuyentran1401/Task-scheduler-problem#3]
@khuyentran1401 

I ran a jupyter notebook of your code to find a few modules missing as well as the Tasks.csv file is missing.

The missing imports can be fixed by adding "!pip install pandas" and "!pip install xlrd" are added to lines 1 and 2 of the code.

That leaves the CSV file which needs to be saved to the repo which I have re-created from your notebook and will submit this for you to approve. Hopefully, this will get the code working.

[Tasks.xlsx](https://github.com/khuyentran1401/Task-scheduler-problem/files/4841153/Tasks.xlsx)

**Comment by khuyentran1401** [comment]
Good fix. I added requirements.txt that you could use `pip install -r requirements.txt` to install all the dependencies needed
