### ISSUE TITLE
Type error in block 9, possible python 2 deprication

### ISSUE THREAD

**Issue by datatalking** [khuyentran1401/Task-scheduler-problem#4]
Once I address [Issue3](https://github.com/khuyentran1401/Task-scheduler-problem/issues/3) the code you provided then generates a type error in block 9 and I'm thinking this is perhaps due to a depreciation of a function of python?

Stacktrace below.

Could I get added as a contributor to this repo?

`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-6034539c9f8d> in <module>
      1 #Define objective
----> 2 prob += lpSum(s[i]*b[t]*y[(i,t)] for i in range(n) for t in range(B))

~/anaconda3/lib/python3.7/site-packages/pulp/pulp.py in lpSum(vector)
   2012     :param vector: A list of linear expressions
   2013     """
-> 2014     return LpAffineExpression().addInPlace(vector)
   2015 
   2016 

~/anaconda3/lib/python3.7/site-packages/pulp/pulp.py in addInPlace(self, other)
    713               or isinstance(other, Iterable)):
    714            for e in other:
--> 715                 self.addInPlace(e)
    716         else:
    717             self.constant += other

~/anaconda3/lib/python3.7/site-packages/pulp/pulp.py in addInPlace(self, other)
    704             self.addterm(other, 1)
    705         elif isinstance(other,LpAffineExpression):
--> 706             self.constant += other.constant
    707             for v,x in other.items():
    708                 self.addterm(v, x)

TypeError: unsupported operand type(s) for +=: 'int' and 'str'
`

**Comment by khuyentran1401** [comment]
Hi Andrew Schell, thank you for suggesting the solutions to the errors. I added you as the contributor. Feel free to create your own branch and push your commits

**Comment by khuyentran1401** [comment]
I have just fixed the errors. Everything should work fine now. Try with pip install -r requirements.txt. Then run the Jupyter notebook again

**Comment by khuyentran1401** [comment]
Thank you for submitting the errors and the suggestions

**Comment by khuyentran1401** [comment]
The error you encountered actually because of the error in your xlsx file. I changed it so s[i] is not the string. And turn the xlsx into two separate csv files
